server:
  port: 8084

spring:
  application:
    name: kodilla-microservice-rating
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8082/eureka
