server:
  port: 8082

spring:
  application:
    name: kodilla-microservice-eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ""
