spring:
  application:
    name: kodilla-microservice-eureka-server
  redis:
    host: localhost
    port: 6379

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
