server:
  port: 8080

spring:
  application:
    name: kodilla-microservice-api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8082/eureka
