server:
  port: 8080

spring:
  application:
    name: kodilla-microservice-api-gateway
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://kodilla-microservice-movie
          predicates:
            - Path=/microservice-movies/**
          filters:
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Authorization
        
        - id: rating-service
          uri: lb://kodilla-microservice-rating
          predicates:
            - Path=/microservice-ratings/**
          filters:
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Authorization

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8082/eureka
